version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test